packages:
  - name: telegram
    functions:
      - name: crawl
        environment:
          TELEGRAM_API_ID: "${TELEGRAM_API_ID}"
          TELEGRAM_API_HASH: "${TELEGRAM_API_HASH}"
          TOKEN: "${TOKEN}"
        runtime: 'python:default'